/** Markdown intro rendered at the top of Scalar / OpenAPI info.description */

export function buildThreadApiDescription(clientUrl: string, baseUrl: string): string {
  return [
    "# Thread API Reference",
    "",
    "> **AI Chief of Staff** for Gmail + Google Calendar — powered by the [Corsair SDK](https://corsair.dev).",
    "> Production flows use live Corsair OAuth + Gmail/Calendar APIs; demo mode uses seeded fixtures when Gmail is not connected.",
    "",
    "---",
    "",
    "## Table of contents",
    "",
    "1. [Judge quick-start](#judge-quick-start)",
    "2. [Architecture](#architecture)",
    "3. [Authentication](#authentication)",
    "4. [Human-in-the-loop queue](#human-in-the-loop-queue)",
    "5. [Corsair Gmail APIs used](#corsair-gmail-apis-used)",
    "6. [Corsair Calendar APIs used](#corsair-calendar-apis-used)",
    "7. [Corsair DB search layer](#corsair-db-search-layer)",
    "8. [MCP server (57 tools)](#mcp-server-57-tools)",
    "9. [Webhooks & real-time sync](#webhooks--real-time-sync)",
    "10. [AI & Agent](#ai--agent)",
    "11. [Error codes & security](#error-codes--security)",
    "12. [Environment variables](#environment-variables)",
    "13. [Related docs](#related-docs)",
    "",
    "---",
    "",
    "## Judge quick-start",
    "",
    "| # | Action | URL |",
    "|---|--------|-----|",
    "| 1 | Open web app | " + clientUrl + " |",
    "| 2 | Demo login (if enabled) | " + clientUrl + "/api-auth/demo?next=/brief |",
    "| 3 | **This Scalar UI** | " + baseUrl + "/docs |",
    "| 4 | Connect Gmail | " + clientUrl + "/api-connect/gmail |",
    "| 5 | Connect Calendar | " + clientUrl + "/api-connect/calendar |",
    "| 6 | Try `GET /inbox/threads` (cookie auth) | Sidebar → Inbox |",
    "| 7 | MCP `tools/list` | `POST " + baseUrl + "/mcp` |",
    "",
    "Walkthrough script: **`JUDGE_WALKTHROUGH.md`** · Demo script: **`DEMO.md`** · Full guide: **`DOCS.md`**",
    "",
    "---",
    "",
    "## Architecture",
    "",
    "```",
    "┌─────────────┐     tRPC/REST      ┌──────────────┐     Corsair SDK     ┌─────────────┐",
    "│  Next.js    │ ─────────────────► │  Thread API  │ ──────────────────► │ Gmail +     │",
    "│  /inbox     │   /api/* + cookies │  Express     │   tenant-scoped   │ Calendar    │",
    "│  /calendar  │                    │  + Queue     │                   │ Google APIs │",
    "│  /agent     │ ◄── SSE /sync ──── │  + MCP       │ ◄── webhooks ──── │             │",
    "└─────────────┘                    └──────────────┘                   └─────────────┘",
    "                                           │",
    "                                           ▼",
    "                                    Postgres (users, queue,",
    "                                    agent sessions, Corsair cache)",
    "```",
    "",
    "| Layer | Technology |",
    "|-------|------------|",
    "| Frontend | Next.js 16, React Query, tRPC client |",
    "| API | Express, tRPC v11, trpc-to-openapi → **this Scalar doc** |",
    "| Integration | **Corsair SDK** — OAuth, encrypted tokens (CORSAIR_KEK), permissions |",
    "| AI | OpenAI gpt-4o-mini — brief, agent, smart replies, ranking |",
    "| MCP | MCP 2024-11-05 — 57 domain tools + official `@corsair-dev/mcp` adapter |",
    "",
    "---",
    "",
    "## Authentication",
    "",
    "### Browser session (web app)",
    "",
    "1. `POST /api/authentication/sign-in` with email/password",
    "2. Response sets httpOnly cookies: `jwt` (access) + `jwt_refresh`",
    "3. All protected routes require valid `jwt` cookie",
    "4. Mutations from browser also require header **`X-Thread-CSRF: 1`** and trusted `Origin`",
    "",
    "### Headless / MCP / scripts",
    "",
    "- Header: `Authorization: Bearer <THREAD_MCP_API_KEY>`",
    "- Env pair: `THREAD_MCP_API_KEY` + `THREAD_MCP_USER_ID` (bound — no arbitrary user impersonation)",
    "- Used for: `POST /mcp`, `POST /mcp/corsair`",
    "",
    "### Corsair OAuth (Gmail + Calendar)",
    "",
    "| Integration | Start URL | Corsair callback |",
    "|-------------|-----------|------------------|",
    "| Gmail | `" + clientUrl + "/api-connect/gmail` | Corsair `generateOAuthUrl` → Google consent |",
    "| Calendar | `" + clientUrl + "/api-connect/calendar` | Same pattern for Calendar plugin |",
    "",
    "Tokens encrypted at rest with **CORSAIR_KEK**. User ID = Corsair tenant ID.",
    "",
    "---",
    "",
    "## Human-in-the-loop queue",
    "",
    "All outbound side effects pass through **`/queue/*`** unless auto-approve is enabled in Settings.",
    "",
    "### Queue item kinds",
    "",
    "| Kind | On approve (Corsair call) | UI signal |",
    "|------|---------------------------|-----------|",
    "| `email_send` | `messages.send` | Queue page |",
    "| `email_draft` | `drafts.create` | Queue page |",
    "| `draft_send` | `drafts.send` | Inbox drafts → Send |",
    "| `calendar_invite` | `events.create` | Dashed block on calendar |",
    "| `meeting_bundle` | `events.create` + `messages.send` | Queue page |",
    "| `calendar_archive` | `events.patch` (reschedule) | Amber overlay |",
    "| `calendar_delete` | `events.delete` | Delete queued overlay |",
    "| `calendar_update` | `events.patch` | Title / description / location |",
    "",
    "### State machine",
    "",
    "```",
    "pending ──approve──► processing ──success──► approved",
    "   │                      │",
    "   └── dismiss ──► dismissed   └── error ──► failed",
    "```",
    "",
    "- Stale `processing` (>15 min) auto-recovers to `pending`",
    "- Email dedupe: identical fingerprint within 10 minutes returns same item",
    "",
    "---",
    "",
    "## Corsair Gmail APIs used",
    "",
    "| Thread endpoint | Corsair / Gmail operation |",
    "|-----------------|---------------------------|",
    "| `GET /inbox/threads` | `threads.list` |",
    "| `GET /inbox/threads/{id}` | `threads.get` |",
    "| `POST /inbox/send` | `messages.send` |",
    "| `POST /inbox/drafts` | `drafts.create` |",
    "| `PUT /inbox/drafts/{id}` | `drafts.update` |",
    "| `POST /inbox/drafts/{id}/send` | direct send (prefer queue) |",
    "| `GET /inbox/labels` | `users.labels.list` |",
    "| `POST /inbox/threads/{id}/labels` | `threads.modify` |",
    "| `POST /inbox/threads/{id}/archive` | `threads.modify` (remove INBOX) |",
    "| `POST /inbox/threads/{id}/star` | `threads.modify` |",
    "| `POST /inbox/threads/batch-modify` | `threads.batchModify` |",
    "| `GET /inbox/db/threads/search` | `corsair.gmail.db.threads.search` |",
    "| `GET /inbox/db/messages/search` | `corsair.gmail.db.messages.search` |",
    "| `GET /inbox/db/drafts/search` | `corsair.gmail.db.drafts.search` |",
    "| `GET /inbox/db/labels/search` | `corsair.gmail.db.labels.search` |",
    "",
    "---",
    "",
    "## Corsair Calendar APIs used",
    "",
    "| Thread endpoint | Corsair / Calendar operation |",
    "|-----------------|------------------------------|",
    "| `GET /calendar/events` | `events.list` |",
    "| `GET /calendar/events/{id}` | `events.get` |",
    "| `POST /calendar/events` | `events.create` (direct — prefer queue) |",
    "| `POST /calendar/events/quick-add` | NLP → queue → `events.create` |",
    "| `PATCH /calendar/events/{id}/reschedule` | `events.patch` (times) |",
    "| `PATCH /calendar/events/{id}/details` | `events.patch` (metadata) |",
    "| `POST /calendar/events/{id}/rsvp` | `events.patch` (attendee response) |",
    "| `POST /calendar/events/{id}/cancel` | `events.patch` (status cancelled) |",
    "| `DELETE /calendar/events/{id}` | `events.delete` |",
    "| `POST /calendar/free-busy` | `freebusy.query` |",
    "| `GET /calendar/db/events/search` | `googlecalendar.db.events.search` |",
    "| `GET /calendar/db/calendars/search` | `googlecalendar.db.calendars.search` |",
    "",
    "---",
    "",
    "## Corsair DB search layer",
    "",
    "After OAuth connect, Corsair syncs entities to Postgres. Search endpoints query **local cache** (<1s, no Gmail quota burn):",
    "",
    "- `/inbox/db/threads/search` — thread metadata",
    "- `/inbox/db/messages/search` — message bodies/snippets",
    "- `/inbox/db/drafts/search` — draft index",
    "- `/inbox/db/labels/search` — label index",
    "- `/calendar/db/events/search` — event index",
    "- `/calendar/db/calendars/search` — calendar list",
    "",
    "Same indexes exposed via MCP tools: `search_*_db` (57-tool parity with Agent).",
    "",
    "---",
    "",
    "## MCP server (57 tools)",
    "",
    "**Endpoint:** `POST " + baseUrl + "/mcp` (JSON-RPC 2.0)",
    "",
    "| Category | Tools (sample) |",
    "|----------|----------------|",
    "| Gmail read | `list_inbox`, `search_inbox`, `get_thread`, `list_drafts`, `list_messages` |",
    "| Gmail write | `queue_email`, `archive_thread`, `star_thread`, `apply_label`, `batch_modify_threads` |",
    "| Calendar | `list_calendar_events`, `queue_calendar_invite`, `quick_add_event`, `respond_to_event` |",
    "| Queue | `list_queue`, `approve_queue_item`, `dismiss_queue_item` |",
    "| AI | `get_daily_brief`, `summarize_thread`, `get_smart_replies`, `get_meeting_prep` |",
    "| DB search | `search_threads_db`, `search_messages_db`, `search_events_db`, … |",
    "",
    "**Official Corsair MCP:** `POST " + baseUrl + "/mcp/corsair` — `list_operations`, `get_schema`, `run_script`",
    "",
    "Full manifest: **`mcp-server.json`** (v2.5.0) · CI parity test: `packages/services/ai/tool-parity.test.ts`",
    "",
    "---",
    "",
    "## Webhooks & real-time sync",
    "",
    "| Webhook | Trigger | Thread behavior |",
    "|---------|---------|-----------------|",
    "| `POST /webhooks/gmail` | Google Pub/Sub | Incremental `history.list` sync via Corsair |",
    "| `POST /webhooks/calendar` | Calendar push channel | Refresh events for tenant |",
    "| `POST /webhooks/corsair` | Corsair internal | Plugin webhook hooks |",
    "",
    "UI listens on `GET /sync/events` (SSE) for cache invalidation — inbox/calendar auto-refresh.",
    "",
    "Daily job renews Gmail watch + Calendar channels (`integration-renewal` with leader lock).",
    "",
    "---",
    "",
    "## AI & Agent",
    "",
    "| Feature | REST | Corsair data source |",
    "|---------|------|---------------------|",
    "| Daily Brief | `GET /brief`, `GET /ai/daily-brief` | threads.list + events.list + OpenAI |",
    "| Inbox ranking | `POST /ai/inbox/rank` | threads + OpenAI |",
    "| Agent chat | `POST /agent/chat` | 57 tools → Corsair |",
    "| Agent stream | `POST /agent/stream` | Same tools, SSE tokens |",
    "| Sessions | `/agent/sessions/*` | Postgres persistence + focus + tool memory |",
    "",
    "Agent guardrails: injection detection, send cap (3/recipient), email body fencing, token budget.",
    "",
    "---",
    "",
    "## Error codes & security",
    "",
    "| Mechanism | Detail |",
    "|-----------|--------|",
    "| Auth errors | 401 — missing/invalid JWT |",
    "| CSRF | 403 — missing `X-Thread-CSRF` on cookie mutations |",
    "| Rate limits | Auth, agent (20/min), MCP (60/min user, 120/min IP) |",
    "| Turnstile | Sign-up/sign-in bot protection |",
    "| Helmet | Security headers on API |",
    "| DOMPurify | HTML email sanitization in web UI |",
    "",
    "tRPC errors sanitized in production — no stack traces leaked.",
    "",
    "---",
    "",
    "## Environment variables",
    "",
    "| Variable | Required | Purpose |",
    "|----------|----------|---------|",
    "| `DATABASE_URL` | Yes | Postgres |",
    "| `JWT_SECRET` | Yes | Session tokens |",
    "| `CORSAIR_KEK` | Yes | Encrypt OAuth tokens |",
    "| `CORSAIR_DEV_KEY` | Yes | Corsair SDK |",
    "| `OPENAI_API_KEY` | For AI | Agent, brief, ranking |",
    "| `CORSAIR_WEBHOOK_SECRET` | Prod | Webhook validation |",
    "| `THREAD_MCP_API_KEY` | MCP scripts | Headless MCP auth |",
    "| `PUBLIC_OPENAPI_DOCS` | Optional | Open `/docs` in prod |",
    "",
    "See **`.env.example`** for full list.",
    "",
    "---",
    "",
    "## Related docs",
    "",
    "| Document | Purpose |",
    "|----------|---------|",
    "| `" + baseUrl + "/docs` | **This Scalar UI** |",
    "| `" + baseUrl + "/openapi.json` | OpenAPI 3.1 JSON |",
    "| `DOCS.md` | Full technical documentation |",
    "| `DEMO.md` | 3-minute judge demo |",
    "| `JUDGE_WALKTHROUGH.md` | Step-by-step scoring guide |",
    "| `README.md` | Setup & architecture |",
    "| `mcp-server.json` | MCP tool manifest |",
  ].join("\n");
}
